<?php
    class Data
    {
        public $option1 = "he most merciful thing in the world, I think, is the inability of the human mind to correlate all its contents.
            We live on a placid island of ignorance in the midst of black seas of infinity, and it was not meant that we
            should voyage far. The sciences, each straining in its own direction, have hitherto harmed us little; but some
            day the piecing together of dissociated knowledge will open up such terrifying vistas of reality, and of our
            frightful position therein, that we shall either go mad from the revelation or flee from the light into the peace
            and safety of a new dark age. -H.P. Lovecraft"
        public $option2 = "Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in
            Liberty, and dedicated to the proposition that all men are created equal.
            Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure. We are met on a great battle-field of that war. We have come to dedicate a portion of that field, as a final resting place for those who here gave their lives that that nation might live. It is altogether fitting and proper that we should do this. But, in a larger sense, we can not dedicate -- we can not consecrate -- we can not hallow -- this ground. The brave men, living and dead, who struggled here, have consecrated it, far above our poor power to add or detract. The world will little note, nor long remember what we say here, but it can never forget what they did here. It is for us the living, rather, to be dedicated here to the unfinished work which they who fought here have thus far so nobly advanced. It is rather for us to be here dedicated to the great task remaining before us -- that from these honored dead we take increased devotion to that cause for which they gave the last full measure of devotion -- that we here highly resolve that these dead shall not have died in vain -- that this nation, under God, shall have a new birth of freedom -- and that government of the people, by the people, for the people, shall not perish from the earth. -Abraham Lincoln"
        public $option3 = "You can't handle the truth! Son, we live in a world that has walls, and those walls have to be guarded by men
             with guns. Who's gonna do it? You? You, Lieutenant Weinberg? I have a greater responsibility than you can possibly fathom. You weep for Santiago and you curse the Marines. You have that luxury. You have the luxury of not knowing what I know, that Santiago's death, while tragic, probably saved lives. And my existence, while grotesque and incomprehensible to you, saves lives! You don't want the truth, because deep down in places you don't talk about at parties, you want me on that wall. You need me on that wall. We use words like 'honor', 'code', 'loyalty'. We use these words as the backbone of a life spent defending something. You use them as a punchline. I have neither the time nor the inclination to explain myself to a man who rises and sleeps under the blanket of the very freedom that I provide, and then questions the manner in which I provide it! I would rather you just said 'thank you', and went on your way. Otherwise, I suggest you pick up a weapon, and stand a post. Either way, I don't give a damn what you think you are entitled to!  - Jack Nicholson"
        public $option4 = "He smiled understandingly-much more than understandingly. It was one of those rare smiles with a quality of
            eternal reassurance in it, that you may come across four or five times in life. It faced–or seemed to face–the whole eternal world for an instant, and then concentrated on you with an irresistible prejudice in your favor. It understood you just as far as you wanted to be understood, believed in you as you would like to believe in yourself, and assured you that it had precisely the impression of you that, at your best, you hoped to convey - F. Scott Fitzgerald"
    }
 ?>
